In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
import os
DIR = '/content/drive/MyDrive/ToiUuLapLich/data'

In [ ]:
%cd '/content/drive/MyDrive/ToiUuLapLich/data'
os.listdir()

## Data Preprocessing

In [46]:
with open("data_10_2_(0).txt", "r") as f:
  r = f.readlines()
  number_subject = int(r[0])
  student_per_subject = [int(u) for u in r[1][:-1].split(" ")]
  number_room = int(r[2])
  place_per_room = [int(u) for u in r[3][:-1].split(" ")]
  number_constrain = int(r[4])

  if(r[-1][-1] != '\n'):
     r[-1] += "\n"

  constrain = []

  for i in range(number_constrain):
    each_constrain = [int(u) for u in r[5+i][:-1].split(" ")]
    constrain.append(each_constrain)
  print(constrain)


[[7, 1], [0, 9], [3, 8], [9, 5], [9, 4], [2, 1], [4, 1], [7, 6], [5, 7], [2, 4], [4, 8], [5, 1], [4, 6], [0, 3], [7, 0], [0, 6], [9, 3], [1, 6], [5, 0], [5, 3], [2, 0], [2, 8], [7, 8], [2, 5], [7, 4], [5, 6], [2, 3], [9, 6], [3, 6], [7, 3], [7, 2], [6, 8], [4, 3], [5, 4], [2, 9], [9, 7], [1, 3]]


In [47]:
import numpy as np
student_per_subject.sort(reverse=True)
student_per_subject = np.asarray(student_per_subject)
print(student_per_subject)
place_per_room.sort(reverse=True)
place_per_room = np.asarray(place_per_room)
print(place_per_room)

[38 38 38 35 34 34 29 28 27 22]
[48 41]


In [54]:
constrain[0][0]

7

In [59]:
matrix_constrain = np.zeros((number_subject, number_subject))
for iter in constrain:
  i = iter[0]
  j = iter[1]
  matrix_constrain[i][j] = 1
  matrix_constrain[j][i] = 1
matrix_constrain

array([[0., 0., 1., 1., 0., 1., 1., 1., 0., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 0., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 0., 1.],
       [1., 1., 0., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [0., 0., 1., 1., 1., 0., 1., 1., 0., 0.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 0.]])

In [65]:
print(matrix_constrain[2])


[1. 1. 0. 1. 1. 1. 0. 1. 1. 1.]


array([0, 1, 3, 4, 5, 7, 8, 9])

In [73]:
con = np.empty((0,), dtype=int)
sign1 = np.where(matrix_constrain[2] == 1)[0]
con = np.append(con, sign1)
sign2 = np.where(matrix_constrain[5] == 1)[0]
con = np.append(con, sign2)
con = np.unique(con)
con

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Gready

In [77]:
kip = 0
subject_checked = np.zeros((number_subject,))
subject_checked
while(np.sum(subject_checked) < number_subject):
  kip += 1
  iter_room = 0
  iter_sub = 0
  conflict = np.empty((0,), dtype=int)
  while(iter_sub < len(student_per_subject) and (iter_room < len(place_per_room))):
    if (subject_checked[iter_sub] == 1) or (iter_sub in conflict):
      iter_sub += 1;
      continue;
    else:
      if(place_per_room[iter_room] >= student_per_subject[iter_sub]):
        subject_checked[iter_sub] = 1
        # TO-DO ADD CONFLICT
        new_conflict = np.where(matrix_constrain[iter_sub] == 1)[0]
        conflict = np.append(conflict, new_conflict)
        conflict = np.unique(conflict)
        # ADD CONFLICT
        iter_room += 1
        iter_sub += 1
      else:
        iter_sub += 1

print(kip)


7


## Solve