In [235]:

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [236]:

import os
import numpy as np
DIR = '/content/drive/MyDrive/exam-scheduling/data'
%cd '/content/drive/MyDrive/exam-scheduling/data'

/content/drive/MyDrive/exam-scheduling/data


In [237]:
def read_data(data_file_name):
  with open(data_file_name, "r") as f:
    r = f.readlines()
    number_subject = int(r[0])
    student_per_subject = [int(u) for u in r[1][:-1].split(" ")]
    number_room = int(r[2])
    place_per_room = [int(u) for u in r[3][:-1].split(" ")]
    number_constrain = int(r[4])

    # student_per_subject.sort(reverse=True)
    student_per_subject = np.asarray(student_per_subject)
    # place_per_room.sort(reverse=True)
    place_per_room = np.asarray(place_per_room)

    if(r[-1][-1] != '\n'):
      r[-1] += "\n"

    constrain = []
    for i in range(number_constrain):
      each_constrain = [int(u) for u in r[5+i][:-1].split(" ")]
      constrain.append(each_constrain)

    matrix_constrain = np.zeros((number_subject, number_subject))
    for iter in constrain:
      i = iter[0]
      j = iter[1]
      matrix_constrain[i][j] = 1
      matrix_constrain[j][i] = 1
        
    return number_subject, student_per_subject, number_room, place_per_room, number_constrain, constrain, matrix_constrain

# TEST
N, d , M, c, number_constrain, constrain, matrix_constrain = read_data(f'{DIR}/data_10_2_(0).txt')

In [238]:
print(matrix_constrain)

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 1. 1. 0.]]


In [239]:

assign=np.full((N),-1)
# print(assign[0])
room=np.full((N,M),-1)
# print(room)
# day=[][]
day=np.full((N,N),-1)
# back=[][]
ans=9999
cf=[]
for i in range(N):
  cf_row=[]
  for j in range(N):
    if matrix_constrain[i][j]>0 :
      cf_row.append(j)

  cf.append(cf_row)




In [240]:
print(len(cf[0]))

0


In [241]:
def check( u, kip) :
        if assign[u] >= 0 :
            return 0

        for i in range(len(cf[u])) :
            v = cf[u][i]
            if (assign[v] == kip) :
                return 0
    

        return 1
    

In [242]:
def checkN( u, ngay) :

        for i in range(N) :

            if matrix_constrain[u][i] > 0 :
                if day[u][i]==ngay or day[i][u]==ngay :
                  return 0

        return 1
    

In [243]:
flag=0

In [244]:
def dfs(u,  kip) :
        global ans
        global flag
        if (u == N) :
            ans = min(9999, kip)

            return

        if(kip > ans) :

            return
        
        for i in range(M):

         if (room[kip][i] == -1):

            for j in range(N):

              if (check(j,kip) and d[j]<=c[i]  ):
                

                    assign[j] = kip

                    room[kip][i] = j

                    dfs(u+1, kip)

                    assign[j] = -1

 
                    room[kip][i] = -1
                

        dfs(u,kip+1)

        return
    

In [245]:

def solve() :
        # long startTime = System.currentTimeMillis()
        dfs(0,0)
        # long endTime = System.currentTimeMillis()
        # System.out.println("\nBacktracking duration = "+(endTime - startTime)+" ms")
        if (ans != 9999) :
            print("Objective value = " )
            print(ans+1)
        else  :
            print("No solution")
        
    

In [246]:
import time
start_time = time.time()
solve()
end_time = time.time()

#tính thời gian chạy của thuật toán Python
elapsed_time = end_time - start_time
print ("elapsed_time:{0}".format(elapsed_time) + "[sec]")


Objective value = 
3
elapsed_time:0.06309318542480469[sec]
